---
- name: Copy backend dir
  become: yes
  file:
    path: /home/ubuntu/backend
    state: directory

- name: Copy dist folder
  become: yes
  copy:
    src: artifact.tar.gz
    dest: /home/ubuntu/backend/artifact.tar.gz
    force: yes

- name: Copy env file
  become: yes
  copy:
    src: .env
    dest: /home/ubuntu/backend/.env
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Start the application
  become: yes
  shell: |
    args:
      executable: /bin/bash
    pwd
    ls -al
    cd /home/ubuntu/backend
    echo It works > testit.txt
    tar -xvf artifact.tar.gz
    npm install
    sleep 5
    pm2 start npm --no-automation --name "backend" -- run start