AWSTemplateFormatVersion: 2010-09-09
Description: >
  This stack will create ProgreSQL RDS Database
Parameters:
  DBName:
    Description: username for the database
    Type: String
    Default: udagram-purpose
  DBMasterUsername:
    Description: The master username for the DB
    Type: String
    Default: dbuser
  DBPassword:
    Description: Password to connect to DB
    Type: String
    Default: DB_PASSWORD
  DBAllocatedStorage:
    Description: The Size of the Database in Gib
    Type: Number
    Default: 20
  
Resources:
  RDSDBSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SG to control access to PostgreSQL RDS DB
      GroupName: PostgreSQL SG
      SecurityGroupIngress:
      - FromPort: 5432
        IpProtocol: TCP
        ToPort: 5432
        CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: Postgres-RDS-SG
  RDSDB:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: PostgreSQL
      EngineVersion: 12.5-R1
      DBInstanceClass: db.t2.micro
      DBName: !Ref DBName
      MasterUsername: !Ref DBMasterUsername
      MasterUserPassword: !Ref DBPassword
      Port: 5432
      PubliclyAccessible: yes
      AvailabilityZone: us-east-1a
      # VPCSecurityGroups:
      AllocatedStorage: !Ref DBAllocatedStorage
      DBSecurityGroups:
      - Ref: RDSDBSG
      Tags:
        - Key: Name
          Value: PostgreSQL-RDS-DB

Outputs:
  DBPort:
    Description: Port to connect to DBInstance
    Value: !GetAtt RDSDB.Endpoint.Port
  DBPublicDNSName:
    Description: The Public DNSName of the DB Instance
    Value: !GetAtt RDSDB.Endpoint.Address
  
