AWSTemplateFormatVersion: 2010-09-09
Description: >
  An S3 bucket that serve as origin for cloudfront
  
Parameters:
  ProjectName:
    Description: Title of the project stack will be applied to
    Type: String
    Default: Udapeople
  S3BucketName:
    Description: The bucket name that hold app artifacts
    Type: String
    Default: udapeople
  BucketID:
    Description: A random string to make bucket name unique
    Type: String
    
 
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${S3BucketName}-${BucketID}

Outputs:
  S3BucketName:
    Description: The name of the S3 bucket
    Value: !Ref S3Bucket
    Export:
      Name: !Sub ${ProjectName}-Initial-S3-BucketName

  S3DomainName:
    Description: Origin url for access the bucket, origin to cloudfront
    Value: !GetAtt S3Bucket.DomainName
    Export:
      Name: !Sub ${ProjectName}-Initial-S3-DomainName
