AWSTemplateFormatVersion: 2010-09-09
Description: >
  An S3 bucket that serve as origin for cloudfront
  
Parameters:
  ProjectName:
    Description: Title of the project stack will be applied to
    Type: String
    Default: Udapeople
  EnvironmentName:
    Description: The environmnt the the stack is being use in
    Type: String
    Default: Dev
  S3BucketName:
    Description: The bucket name that hold app artifacts
    Type: String
    Default: udapeople-568be999-1831-473c-9750-d7d4ccb70533
    
 
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3BucketName
     
Outputs:
  S3BucketName:
    Description: The name of the S3 bucket
    Value: !Ref S3Bucket
    Export:
      Name: !Sub ${ProjectName}-${EnvironmentName}-S3-BucketName
